const express = require('express');
const bodyParser = require('body-parser');
const cookieSession = require('cookie-session');
const bcrypt = require('bcrypt');
const methodOverride = require('method-override');
const {generateRandomString, findUser, findEmail, urlsInDatabase, loopID} = require('./helpers');


const app = express();
const PORT = 8080;

app.set("view engine", "ejs");
app.use(bodyParser.urlencoded({extended: true}));
app.use(cookieSession({
  name: 'session',
  keys: ['key1', 'key2'],
  maxAge: 24 * 60 * 60 * 1000
}));
app.use(methodOverride('_method'));

//initializes a urlDatabase
const urlDatabase = {
};

//initializes a user database, with an initial admin entry for testing purposes
const users = {
  "admin": {
    id: "admin",
    email: "admin@tinyapp.com",
    password: bcrypt.hashSync("password", 10)
  },
};

//root entry at server redirects to homepage
app.get("/", (req, res) => {
  res.redirect('/urls');
});

//provides json file access to admin for troubleshooting and data purposes; redirects to homepage if not admin
app.get("/urls.json", (req, res) => {
  if (!req.session.usrID) {
    res.redirect('/urls');
  }
  if (findUser(req.session.usrID, users)['id'] !== 'admin') {
    res.redirect('/urls');
  }
  res.json(urlDatabase);
});

//serves main page, which provides a user with their listed urls, and if not logged in directs a client to login or register
app.get('/urls', (req, res) => {
  const userUrls = urlsInDatabase(req.session.usrID, 'userID', urlDatabase);
  const templateVars = { urls: userUrls, visits: urlDatabase, username: (findUser(req.session.usrID, users))};
  res.render('urls_index', templateVars);
});

//provides users with a page and form to create a new shortURL
app.get("/urls/new", (req, res) => {
  const templateVars = {username: (findUser(req.session.usrID, users))};
  if (!templateVars['username']) {
    return res.redirect('/urls');
  }
  res.render("urls_new", templateVars);
});

//serves a registration page for unregistered/logged in users
app.get("/register", (req, res) => {
  const templateVars = {username: (findUser(req.session.usrID, users))};
  res.render("urls_registration", templateVars);
});

//serves a login page for previously registered users
app.get("/login", (req, res) => {
  const templateVars = {username: (findUser(req.session.usrID, users))};
  res.render("login.ejs", templateVars);
});

//serves an analytics page for each shortURL generated by a user
app.get('/urls/:shortURL/analytics', (req, res) => {
  if (!urlDatabase[req.params.shortURL]) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 404 - Page Not Found'};
    return res.status(404).render('error', templateVars);
  }
  if (!req.session.usrID) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 401 - Please Login'};
    return res.status(401).render('error', templateVars);
  }
  if (urlDatabase[req.params.shortURL]['userID'] !== req.session.usrID) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 401 - Incorrect user profile'};
    return res.status(401).render('error', templateVars);
  }
  const longURL = urlDatabase[req.params.shortURL]['longURL'];
  const templateVars = { username: (findUser(req.session.usrID, users)), shortURL: req.params.shortURL, longURL: `${longURL}`, visits: urlDatabase[req.params.shortURL]['visits'], unique: urlDatabase[req.params.shortURL]['unique'], eachVisit: urlDatabase[req.params.shortURL]['eachVisit']};
  res.render("urls_analytics", templateVars);
});

//provides a view page for a shortURL with edit and delete options
app.get('/urls/:shortURL', (req, res) => {
  if (!urlDatabase[req.params.shortURL]) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 404 - Page Not Found'};
    return res.status(404).render('error', templateVars);
  }
  if (!req.session.usrID) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 401 - Please Login'};
    return res.status(401).render('error', templateVars);
  }
  if (urlDatabase[req.params.shortURL]['userID'] !== req.session.usrID) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 401 - Incorrect user profile'};
    return res.status(401).render('error', templateVars);
  }
  const longURL = urlDatabase[req.params.shortURL]['longURL'];
  const templateVars = { username: (findUser(req.session.usrID, users)), shortURL: req.params.shortURL, longURL: `${longURL}`};
  res.render("urls_show", templateVars);
});

//functions as link redirection when following a shortened URL - redirects to the original longURL; publicly available link
app.get("/u/:shortURL", (req, res) => {
  if (!urlDatabase[req.params.shortURL]) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 404 - Page not found'};
    return res.status(404).render('error', templateVars);
  }
  //increments the visits statistic every time link is followed
  urlDatabase[req.params.shortURL]['visits']++;

  //if the visitor is new, will assign a visitor id cookie, and increase the unique visitor count
  if (!req.session.visitor) {
    //refactor loop code to modularize in helpers (take in database in generaterandomstring)
    let visitorID = generateRandomString();
    req.session.visitor = visitorID;
    urlDatabase[req.params.shortURL]['unique']++;
  }

  //adds the date stamp and visitor id of every visitor to this link
  urlDatabase[req.params.shortURL]['eachVisit'].push("" + req.session.visitor + " visited on " + Date());

  const longURL = urlDatabase[req.params.shortURL]['longURL'];
  res.redirect(longURL);
});

//allows a user to add a new shortURL from a given url
app.post("/urls", (req, res) => {
  let newShort = generateRandomString();
  //check if there is a duplicate shortURL name and re-generates if found
  loopID(newShort, urlsInDatabase(newShort, 'id', urlDatabase));
  urlDatabase[newShort] = {longURL: req.body.longURL, userID: req.session.usrID, visits: 0, unique: 0, eachVisit: []};
  res.redirect(`/urls/${newShort}`);
});

//allows a user to hit the delete button and delete the shortURL from the urldatabase. This completely removes the entry from the database.
app.delete("/urls/:shortURL/delete", (req, res) => {
  if (urlDatabase[req.params.shortURL]['userID'] !== req.session.usrID) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 401 - Invalid User'};
    return res.status(401).render('error', templateVars);
  }
  delete urlDatabase[req.params.shortURL];
  res.redirect("/urls");
});

//allows the user to edit the given longURL to a new URL. This does not reset the analytics counter of visits to a given shortURL.
app.put("/urls/:shortURL/", (req, res) => {
  if (urlDatabase[req.params.shortURL]['userID'] !== req.session.usrID) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 401 - Invalid User'};
    return res.status(401).render('error', templateVars);
  }
  urlDatabase[req.params.shortURL]['longURL'] = req.body.longURL;
  res.redirect("/urls");
});

//allows a user to login by providing a username and password. Checks if these are in userdatabase, and if they match.
app.post("/login", (req, res) => {
  const username = req.body.email;
  const password = req.body.password;
  if (!findEmail(username, users)) {
    const templateVars = {username: undefined, errorCode: 'Error 403 - User Not Found'};
    return res.status(403).render('error', templateVars);
  }
  const userPass = findEmail(username, users)['password'];
  if (!bcrypt.compareSync(password, userPass)) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 403 - Password Does Not Match'};
    return res.status(403).render('error', templateVars);
  }
  const userID = findEmail(username, users)['id'];
  req.session.usrID = userID;
  res.redirect("/urls");
});

//logs a user out and clears the cookies of their session
app.post("/logout", (req, res) => {
  res.clearCookie('session');
  res.redirect("/urls");
});

//allows a new user to register for site use, and creates a unique userID for them
app.post('/register', (req, res) => {
  const username = req.body.email;
  const password = req.body.password;
  if (!username || !password) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 400 - Field Left Blank'};
    return res.status(400).render('error', templateVars);
  }
  if (findEmail(username, users)) {
    const templateVars = {username: (findUser(req.session.usrID, users)), errorCode: 'Error 400 - User Email Already Exists'};
    return res.status(400).render('error', templateVars);
  }
  const hashedPassword = bcrypt.hashSync(password, 10);
  let userID = generateRandomString();
  //checks for duplicate userID, and regenerates until novel
  loopID(userID, urlsInDatabase(userID, 'id', users));
  users[userID] = {'id': userID, 'email': username, 'password': hashedPassword};
  req.session.usrID = userID;
  res.redirect('/urls');
});

//initiates server
app.listen(PORT, () => {
  console.log(`Tinyapp listening on port ${PORT}!`);
});